### ISSUE TITLE
Тесты падают

### ISSUE THREAD

**Issue by RichCake** [scriptoxin/yandex-liceum-go-calc#1]
Привет. Проверяю твой проект. Все замечательно 🥇, но тесты падают. ГПТ предложил `strings.TrimSpace(rr.Body.String())`. А еще в `internal/handlers/calculate.go` в строке 14 возвращается строка, а не JSON. Поставил 96 баллов, если исправишь недочеты, будет 💯

**Comment by scriptoxin** [comment]
Спасибо за обратную связь!) На новогодних займусь полноценным рефакторингом, ибо есть моменты, которые хочу существенно переписать (в том числе упомянутые). Нынешнего балла более чем достаточно, крайне признателен и успехов на следующих модулях;)

**Comment by RichCake** [comment]
С наступающим тогда)
